services:
  backend-node:
    build: .
    env_file: .env
    environment:
      DRAGONFLY_URL: redis://dragonfly:6379
    depends_on:
      - dragonfly
    ports:
      - "4200:4200"
    volumes:
      - backend-node-data:/data
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    command: ["--logtostderr"]
    ports:
      - "6380:6379"
    volumes:
      - backend-node-dragonfly:/data

volumes:
  backend-node-data:
  backend-node-dragonfly:
