param(
  [Parameter(Mandatory = $true)][string]$ManagementUrl,
  [Parameter(Mandatory = $true)][string]$NodeId,
  [Parameter(Mandatory = $true)][string]$NodeEnrollmentToken,
  [Parameter(Mandatory = $true)][string]$NodePublicUrl,
  [Parameter(Mandatory = $true)][string]$DragonflyUrl,
  # Must match NODE_API_SECRET on the management server (generated by setup-management.ps1)
  [Parameter(Mandatory = $true)][string]$NodeApiSecret,
  [Parameter(Mandatory = $false)][string]$CorsAllowedOrigins = "",
  [switch]$RegisterNow
)

$ErrorActionPreference = "Stop"

if ($NodeApiSecret.Length -lt 32) {
  Write-Error "NodeApiSecret must be at least 32 characters. Copy the NODE_API_SECRET value printed by setup-management.ps1."
  exit 1
}

@"
PORT=4200
NODE_ID=$NodeId
NODE_ENROLLMENT_TOKEN=$NodeEnrollmentToken
NODE_PUBLIC_URL=$NodePublicUrl
MANAGEMENT_URL=$ManagementUrl
TENANT_ID=default
DRAGONFLY_URL=$DragonflyUrl
NODE_API_SECRET=$NodeApiSecret
CORS_ALLOWED_ORIGINS=$CorsAllowedOrigins
"@ | Set-Content -Path ".env" -Encoding utf8

Write-Host ""
Write-Host "=== 1Patch Backend Node Setup Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Wrote .env" -ForegroundColor Cyan
Write-Host "Node ID:        $NodeId"
Write-Host "Management URL: $ManagementUrl"
Write-Host "Node public URL:$NodePublicUrl"
Write-Host "DragonflyDB:    $DragonflyUrl"
if ($CorsAllowedOrigins) {
  Write-Host "CORS Origins:   $CorsAllowedOrigins"
}
Write-Host ""

if ($RegisterNow) {
  Write-Host "Registering node with management server..." -ForegroundColor Cyan
  try {
    $body = @{
      nodeId          = $NodeId
      enrollmentToken = $NodeEnrollmentToken
      version         = "0.1.0"
      capacity        = @{ packageCache = "local" }
    } | ConvertTo-Json
    Invoke-RestMethod -Method Post "$($ManagementUrl.TrimEnd('/'))/nodes/register" `
      -ContentType "application/json" `
      -Headers @{ "x-node-api-secret" = $NodeApiSecret } `
      -Body $body | Out-Null
    Write-Host "Node registration accepted by management server." -ForegroundColor Green
  } catch {
    Write-Host "Registration failed — start the backend node and it will retry automatically." -ForegroundColor Yellow
    Write-Host $_.Exception.Message
  }
} else {
  Write-Host "Next: npm install && npm run build && npm start" -ForegroundColor Cyan
  Write-Host "The node will register with management automatically on first start."
}
