import { Body, Controller, Logger, Post, UnauthorizedException } from '@nestjs/common';
import { IsString } from 'class-validator';
import { TaskStore } from './tasks/task.store';
import { SignedEnvelope, KillSwitchState } from './types';
import { createHash, timingSafeEqual } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

class DecommissionDto {
  @IsString()
  nodeId!: string;

  /**
   * Per-node decommission token generated by the management server at registration.
   * Management sends the plaintext token; we compare its SHA-256 hash with
   * our locally stored NODE_DECOMMISSION_TOKEN_HASH. This token is unique per node so it
   * cannot be used to decommission any other node.
   */
  @IsString()
  decommissionToken!: string;
}

@Controller('/node')
export class NodeControlController {
  private readonly logger = new Logger(NodeControlController.name);

  /**
   * Creates a NodeControlController instance with its required collaborators.
   *
   * @param tasks tasks supplied to the function.
   */
  constructor(private readonly tasks: TaskStore) {}


  /**
   * Handles the decommission operation for NodeControlController.
   *
   * @param dto Request payload or data transfer object.
   * @returns The result produced by the operation.
   */
  @Post('/decommission')
  async decommission(@Body() dto: DecommissionDto) {
    if (process.env.NODE_ID && dto.nodeId !== process.env.NODE_ID) {
      this.logger.warn(`Rejected decommission request for node ${dto.nodeId}; this node is ${process.env.NODE_ID}`);
      return { cleared: false, reason: 'node_id_mismatch' };
    }

    
    const stored = process.env.NODE_DECOMMISSION_TOKEN_HASH ?? '';
    if (!stored) {
      this.logger.warn('NODE_DECOMMISSION_TOKEN_HASH is not set — cannot verify decommission request');
      return { cleared: false, reason: 'decommission_token_not_configured' };
    }

    const supplied = Buffer.from(hashToken(dto.decommissionToken));
    const expected = Buffer.from(stored);
    const valid = supplied.length === expected.length && timingSafeEqual(supplied, expected);
    if (!valid) {
      this.logger.warn(`Decommission request rejected — invalid token for node ${dto.nodeId}`);
      return { cleared: false, reason: 'invalid_decommission_token' };
    }

    this.logger.warn(`Decommission authorised for node ${dto.nodeId}. Clearing local registration config.`);
    await clearNodeConfiguration();
    process.env.NODE_ID = '';
    process.env.NODE_ENROLLMENT_TOKEN = '';
    process.env.MANAGEMENT_URL = '';
    process.env.NODE_PUBLIC_URL = '';
    process.env.NODE_DECOMMISSION_TOKEN_HASH = '';
    this.logger.warn('Local node registration config cleared. Restart before re-enrolling.');
    return { cleared: true, restartRecommended: true };
  }

  /**
   * Called by the management server (over mTLS) to push a signed kill switch
   * state update to this node. The management server authenticates with its
   * Vault-issued client cert. An additional shared management-to-node API secret
   * (NODE_MGMT_SECRET) is required to prevent any node from accepting forged
   * kill-switch payloads from non-management sources.
   */
  @Post('/kill-switch')
  async killSwitch(
    @Body() body: { secret: string; envelope: SignedEnvelope<KillSwitchState> },
  ) {
    const expected = process.env.NODE_MGMT_SECRET ?? '';
    if (!expected) {
      this.logger.error('NODE_MGMT_SECRET is not configured - refusing kill-switch push');
      throw new UnauthorizedException('NODE_MGMT_SECRET is not configured on this node');
    }
    const supplied = Buffer.from(body.secret ?? '');
    const stored   = Buffer.from(expected);
    const ok = supplied.length === stored.length &&
               timingSafeEqual(supplied, stored);
    if (!ok) {
      this.logger.warn('Kill-switch push rejected - invalid NODE_MGMT_SECRET');
      throw new UnauthorizedException('Invalid management secret');
    }
    await this.tasks.setKillSwitchEnvelope(body.envelope);
    this.logger.warn(
      `Kill switch state updated: tenantId=${body.envelope.payload.tenantId} ` +
      `active=${body.envelope.payload.active}`,
    );
    return { accepted: true };
  }
}

/**
 * Handles the clear node configuration operation.
 */
async function clearNodeConfiguration() {
  const envPath = join(process.cwd(), '.env');
  const existing = await readFile(envPath, 'utf8').catch(() => '');
  const keysToClear = new Set([
    'NODE_ID',
    'NODE_ENROLLMENT_TOKEN',
    'NODE_PUBLIC_URL',
    'MANAGEMENT_URL',
    'NODE_DECOMMISSION_TOKEN_HASH',
  ]);
  const seen = new Set<string>();
  const lines = existing
    .split(/\r?\n/)
    .filter((line, index, all) => line.length > 0 || index < all.length - 1)
    .map((line) => {
      const match = /^([^=#\s]+)=/.exec(line);
      if (!match) return line;
      const key = match[1];
      if (!keysToClear.has(key)) return line;
      seen.add(key);
      return `${key}=`;
    });
  for (const key of keysToClear) {
    if (!seen.has(key)) lines.push(`${key}=`);
  }
  await writeFile(envPath, `${lines.join('\n')}\n`, 'utf8');
}

/**
 * Produces the hash token security value.
 *
 * @param token Token used to authenticate or authorize the operation.
 * @returns The result produced by the operation.
 */
function hashToken(token: string): string {
  return createHash('sha256').update(token).digest('hex');
}
